const $=id=>document.getElementById(id);const normalize=s=>s.toLowerCase().replace(/[^a-z0-9]/g,'');let attempts=[],finished=false,busy=true,serverResult=null,serverClues=[],selected=null,searchRevision=0;
const secure=new window.HardleSecureGame('artist');
function stockholmDate(now=new Date()){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Stockholm',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(now);const get=type=>parts.find(p=>p.type===type).value;return get('year')+'-'+get('month')+'-'+get('day')}
const puzzleDate=stockholmDate();const storageKey='hardle-artist-daily-v1-'+puzzleDate+(puzzleDate==='2026-10-06'?'-refresh-1515':'');
async function restoreProgress(){busy=true;try{const state=await secure.start();serverClues=state.public_payload.clues;attempts=state.guesses.map(g=>({id:g.guess.canonical,name:g.feedback.guessed?.name||'Previous artist guess',won:g.feedback.won}));for(const g of state.guesses)if(g.feedback.clues)serverClues=g.feedback.clues;serverResult=state.completed?{...state.result,completed:true}:null;finished=!!state.completed;busy=false;render();if(finished)showResult()}catch(error){$('message').textContent=error.message;$('guess').disabled=true;$('submit').disabled=true}}
function updateCountdown(){const now=new Date();if(stockholmDate(now)!==puzzleDate){location.reload();return}let low=now.getTime(),high=low+27*3600000;while(high-low>1){const mid=Math.floor((low+high)/2);if(stockholmDate(new Date(mid))===puzzleDate)low=mid;else high=mid}const ms=high-now.getTime();$('daily-countdown').textContent='Next artist in '+[Math.floor(ms/3600000),Math.floor(ms%3600000/60000),Math.floor(ms%60000/1000)].map(n=>String(n).padStart(2,'0')).join(':');}
function renderCountry(node,value){node.replaceChildren();const names={Netherlands:'nl',Denmark:'dk',Australia:'au',Norway:'no',Germany:'de',Belgium:'be',France:'fr',Italy:'it',USA:'us',Ukraine:'ua'};const name=value.replace('Country: ','').replace(/[\u{1F1E6}-\u{1F1FF}]/gu,'').trim();const code=names[name];if(code){const img=document.createElement('img');img.src='/data/flags/'+code+'.svg';img.alt=name+' flag';img.className='countryFlag';node.append(img)}node.append(document.createTextNode(' '+name))}
function render(){const artist={name:serverResult?.answer?.name||'',clues:serverClues};$('counter').textContent=`Attempts: ${attempts.length} / 6`;$('clues').replaceChildren();serverClues.forEach(clue=>{const li=document.createElement('li');if(clue.startsWith('Country: ')){const label=document.createElement('span');label.textContent='Country: ';const country=document.createElement('span');renderCountry(country,clue);li.append(label,country)}else li.textContent=clue;$('clues').append(li)});$('history').replaceChildren();attempts.forEach(name=>{const li=document.createElement('li');li.textContent=name.name+(name.won?' — Correct!':' — Incorrect');$('history').append(li)});$('guess').disabled=finished||busy||!!secure.pending;$('submit').disabled=finished||busy;}

function hideResults(){$('artist-results').hidden=true;$('guess').setAttribute('aria-expanded','false')}
async function searchArtists(){selected=null;const revision=++searchRevision,box=$('artist-results');box.replaceChildren();const q=$('guess').value.trim();if(!q||finished||busy){hideResults();return}try{const data=await secure.request('/api/secure-search',{game:'artist',query:q});if(revision!==searchRevision)return;data.items.filter(artist=>!attempts.some(previous=>previous.id===artist.id)).forEach(artist=>{const button=document.createElement('button');button.type='button';button.className='result';button.textContent=artist.name;button.onclick=()=>{selected=artist;$('guess').value=artist.name;hideResults();$('guess').focus()};box.append(button)});box.hidden=!box.children.length;$('guess').setAttribute('aria-expanded',String(!!box.children.length))}catch(error){$('message').textContent=error.message}}
let artistSearchTimer;
$('guess').addEventListener('input',()=>{selected=null;searchRevision++;clearTimeout(artistSearchTimer);hideResults();artistSearchTimer=setTimeout(searchArtists,250)});
$('guess').addEventListener('keydown',event=>{if(event.key==='Escape')hideResults();if(event.key==='ArrowDown'&&!$('artist-results').hidden){event.preventDefault();$('artist-results').firstElementChild?.focus()}});
$('artist-results').addEventListener('keydown',event=>{if(event.key==='Escape'){hideResults();$('guess').focus()}if(event.key==='ArrowDown'||event.key==='ArrowUp'){event.preventDefault();const sibling=event.key==='ArrowDown'?event.target.nextElementSibling:event.target.previousElementSibling;if(sibling)sibling.focus();else $('guess').focus()}});
document.addEventListener('click',event=>{if(!event.target.closest('.guessBox'))hideResults()});
$('guess-form').addEventListener('submit',async event=>{event.preventDefault();hideResults();if(stockholmDate()!==puzzleDate){location.reload();return}if(finished||busy)return;if(!selected&&!secure.pending){$('message').textContent='Choose an artist from the suggestions.';return}const choice=selected||{id:secure.pending?.guess,name:'Retried guess'};if(!secure.pending&&attempts.some(previous=>previous.id===choice.id)){$('message').textContent='You already guessed that artist.';return}busy=true;render();try{const data=await secure.guess(secure.pending?.guess||choice.id);attempts.push({id:choice?.id||secure.pending?.guess,name:choice?.name||'Retried guess',won:data.won});serverResult=data;if(data.clues)serverClues=data.clues;finished=!!data.completed;$('guess').value='';selected=null;$('message').textContent=data.won?'Correct!':finished?'No attempts left.':'Not quite — a new clue is available.';if(finished)showResult()}catch(error){$('message').textContent=error.message+(secure.pending?' — submit again to retry.':'')}finally{busy=false;render()}});
const artistStatsKey='hardle-artist-stats-v1';let artistStats={played:0,wins:0,streak:0,best:0,lastWin:null,distribution:[0,0,0,0,0,0]};try{const saved=JSON.parse(localStorage.getItem(artistStatsKey)||'null');if(saved)artistStats={...artistStats,...saved}}catch{}
function recordArtistResult(){}
function renderArtistStats(){recordArtistResult();$('artist-stats').replaceChildren();for(const [label,value] of [['Played',artistStats.played],['Win %',artistStats.played?Math.round(artistStats.wins/artistStats.played*100):0],['Streak',artistStats.streak],['Best streak',artistStats.best],['Score',serverResult?.score||0],['Today',attempts.length+'/6']]){const div=document.createElement('div'),b=document.createElement('b'),span=document.createElement('span');b.textContent=value;span.textContent=label;div.append(b,span);$('artist-stats').append(div)}$('artist-distribution').replaceChildren();const max=Math.max(1,...artistStats.distribution);artistStats.distribution.forEach((count,i)=>{const bar=document.createElement('div');bar.style.width=Math.max(12,count/max*100)+'%';bar.textContent=(i+1)+': '+count;$('artist-distribution').append(bar)})}
$('artist-copy').onclick=async()=>{try{await navigator.clipboard.writeText('HARDLE Guess the Artist '+puzzleDate+' '+attempts.length+'/6\n'+attempts.map(name=>name.won?'🟩':'⬛').join(''));$('artist-copy').textContent='Copied!'}catch{$('artist-copy').textContent='Copy failed'}};
function showResult(){renderArtistStats();const won=!!serverResult?.won;if(!won){try{localStorage.setItem('hardle-failed-artist-'+puzzleDate,'1')}catch{}}document.querySelector('.correctBox').classList.toggle('loss',!won);const feedback=!won?['BETTER LUCK TOMORROW!','🔴','red']:attempts.length<=2?['PERFECT!','🟢🔥','green']:attempts.length===3?['AMAZING!','🟢','green']:attempts.length===4?['NICE!','🟡','yellow']:attempts.length===5?['WELL DONE!','🟠','orange']:['JUST IN TIME!','🔥','orange'];document.querySelector('.correctBox').dataset.feedback=feedback[2];$('result-title').textContent=feedback[0];document.querySelector('.correctIcon').textContent=feedback[1];document.querySelector('.correctSub').textContent=won?'You found today’s artist in '+attempts.length+'/6 attempts!':'Here is today’s artist. Try again tomorrow!';if(won){try{localStorage.setItem('hardle-completed-artist-'+puzzleDate,'1')}catch{}}const artist={name:serverResult?.answer?.name||'',clues:serverClues};const link=$('artist-spotify');link.hidden=true;link.removeAttribute('href');link.textContent='Open artist on Spotify ↗';fetch('/api/spotify-artist?artist='+encodeURIComponent(artist.name)).then(r=>r.ok?r.json():null).then(data=>{if(data&&/^https:\/\/open\.spotify\.com\/artist\/[A-Za-z0-9]{22}$/.test(data.spotify_url)){link.href=data.spotify_url;link.hidden=false;link.textContent='Open artist on Spotify ↗'}}).catch(()=>{});$('result-artist').textContent=artist.name;$('result-guesses').textContent=attempts.length+' / 6';$('result-genre').textContent=(serverResult?.answer?.clues?.[4]||'Genre: —').replace('Genre: ','');renderCountry($('result-country'),serverResult?.answer?.clues?.[3]||'Country: —');$('result-modal').classList.add('show');$('result-modal').setAttribute('aria-hidden','false');$('result-close').focus()}
function closeResult(){$('result-modal').classList.remove('show');$('result-modal').setAttribute('aria-hidden','true')}
$('result-close').addEventListener('click',closeResult);$('result-modal').addEventListener('click',e=>{if(e.target===$('result-modal'))closeResult()});document.addEventListener('keydown',e=>{if(!$('result-modal').classList.contains('show'))return;if(e.key==='Escape')closeResult();if(e.key==='Tab'){const last=$('result-close'),first=$('artist-spotify').hidden?last:$('artist-spotify');if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
restoreProgress();recordArtistResult();if(finished)showResult();updateCountdown();setInterval(updateCountdown,1000);
document.addEventListener('visibilitychange',()=>{if(!document.hidden)updateCountdown()});window.addEventListener('focus',updateCountdown);

