'use strict';
window.HardleScore={
  attempts(won,count){return won?([1000,850,700,550,400,250,100][count-1]||0):0},
  record(game,date,points){try{const key='hardle-score-v2-'+game+'-'+date;if(localStorage.getItem(key)!==null)return;localStorage.setItem(key,JSON.stringify({points:Math.max(0,Math.min(1000,points))}))}catch{}},
  total(game){let total=0;try{for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(key.startsWith('hardle-score-v2-'+game+'-')){const row=JSON.parse(localStorage.getItem(key));if(Number.isFinite(row?.points))total+=row.points}}}catch{}return total},
  dailyTotal(date){try{const results=JSON.parse(localStorage.getItem('hardle-menu-result-'+date)||'{}');return Object.values(results).reduce((total,result)=>{const points=Number(result?.score);return total+(Number.isFinite(points)?Math.max(0,Math.min(1000,points)):0)},0)}catch{return 0}},
  async verifiedDailyTotal(date){let session;try{session=JSON.parse(localStorage.getItem('hardle-auth-v1')||'null')}catch{}const config=window.HardleAccountConfig;if(!session?.access_token)return this.dailyTotal(date);if(!config)throw Error('Account configuration unavailable');const response=await fetch(config.url+'/rest/v1/rpc/hardle_my_stats',{method:'POST',headers:{apikey:config.key,Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'},body:'{}',signal:AbortSignal.timeout(10000)});if(!response.ok)throw Error('Daily score unavailable');const stats=await response.json();if(!Number.isFinite(Number(stats.dailyScore)))throw Error('Invalid daily score');if(JSON.parse(localStorage.getItem('hardle-auth-v1')||'null')?.access_token!==session.access_token)throw Error('Account changed');return Number(stats.dailyScore)},
  totalAll(){let total=0;try{for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(key.startsWith('hardle-score-v2-')){const row=JSON.parse(localStorage.getItem(key));if(Number.isFinite(row?.points))total+=row.points}}}catch{}return total}
};
